"""Добавлено поле даты создания заявки

Revision ID: 286dfd33afc7
Revises: d4bd85dcfb4b
Create Date: 2024-11-28 23:24:12.588696

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '286dfd33afc7'
down_revision = 'd4bd85dcfb4b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('request', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_created', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('request', schema=None) as batch_op:
        batch_op.drop_column('date_created')

    # ### end Alembic commands ###
